### ISSUE TITLE
beatmap 1231758: java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"

### ISSUE THREAD

**Issue by omkelderman** [Tillerino/Tillerinobot#159]
```
08:28:43.848 WARN  HttpChannel  - /beatmapinfo?k=**key**&beatmapid=1231758&mods=0
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"
        at org.glassfish.jersey.jetty.JettyHttpContainer.handle(JettyHttpContainer.java:197)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at com.github.francesco149.koohii.Koohii$Parser.timing(Koohii.java:498)
        at com.github.francesco149.koohii.Koohii$Parser.map(Koohii.java:592)
        at tillerino.tillerinobot.diff.Koohii.calculate(Koohii.java:37)
        at org.tillerino.osupp.DiffEstimateBuilder.getFixedData(DiffEstimateBuilder.java:281)
        at org.tillerino.osupp.DiffEstimateBuilder.calculateSecondGen(DiffEstimateBuilder.java:109)
        at org.tillerino.osupp.DiffEstimateBuilder.calculateDiffEstimate(DiffEstimateBuilder.java:403)
        at org.tillerino.osupp.DiffEstimateProvider.loadOrCalculate(DiffEstimateProvider.java:77)
        at org.tillerino.osupp.BackendImplementation.getEstimates(BackendImplementation.java:168)
        at org.tillerino.osupp.BackendImplementation.loadBeatmap(BackendImplementation.java:196)
        at tillerino.tillerinobot.rest.BeatmapInfoService$1$1.call(BeatmapInfoService.java:80)
        at tillerino.tillerinobot.rest.BeatmapInfoService$1$1.call(BeatmapInfoService.java:75)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
08:28:43.868 WARN  HttpChannel  - Could not send response error 500: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "SliderBorder:BMAPI.Colour"
```

**Comment by Tillerino** [comment]
See Francesco149/koohii#6
